---

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6
  NewCops: enable

### METRICS ###
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

### RPSEC ###
RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

### STYLES ###
Style/Documentation:
  Enabled: false
