require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
