---

require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6
  NewCops: enable

### METRICS ###
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - validates_timeliness-mongoid.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/**/*

### RPSEC ###
RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

### STYLES ###
Style/Documentation:
  Enabled: false
